language: node_js

node_js:
  - 'stable'

branches:
  only:
  - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

script:
  - "npm run predeploy"
